"""empty message

Revision ID: 536c91a672e3
Revises: 4602359aafb4
Create Date: 2018-08-25 15:04:33.815149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536c91a672e3'
down_revision = '4602359aafb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user-admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-admin',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"user-admin_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user-admin_pkey'),
    sa.UniqueConstraint('password', name='user-admin_password_key'),
    sa.UniqueConstraint('username', name='user-admin_username_key')
    )
    op.drop_table('user_admin')
    # ### end Alembic commands ###
